Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,9 +22,10 @@ jobs:
         name: Get latest tag
         run: |
           #!/bin/bash
-          latest_tag="0.1.240" # Temporary fix
+          url="https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/"
+          resp=$(curl $url)
+          latest_tag=echo "$resp" | grep -o 'href="[^"]*' | tail -c +98 | sed 's/...$//'
           [ -z "$latest_tag" ] && echo "Tag not found!" && exit 1
-          [[ "$latest_tag" == "null" ]] && echo "Tag not found!" && exit 1
           [[ "$latest_tag" = v* ]] && latest_tag="${latest_tag:1}"
           echo "Found tag: \"${latest_tag}\""
           echo "latest_tag=$latest_tag" >> $GITHUB_ENV
@@ -43,11 +44,11 @@ jobs:
             exit 0
           fi
           loc="${{ env.latest_tag }}"
-          url="https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-${loc}-1"
+          url="https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-winx-${loc}-1"
           echo "Checking if ${url} exists.."
           resp=$(curl -I 2>/dev/null $url | head -1)
           if echo $resp | grep 404 >/dev/null; then
-           echo "exists=true" >> $GITHUB_ENV
+           echo "Download $url not found!" && exit 1
           else
            echo "exists=false" >> $GITHUB_ENV
           fi
